package com.danielmarques.mestredatabuada;

import android.app.*;
import android.os.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    LinearLayout root, content; SharedPreferences p; Random rnd=new Random();
    int coins,level,score,correct,lives,streak,question,table; boolean timed; String child,avatar,username;
    final int NAVY=Color.rgb(18,20,43),BLUE=Color.rgb(39,91,170),GOLD=Color.rgb(255,193,55),GREEN=Color.rgb(35,184,117),ORANGE=Color.rgb(255,139,53),PURPLE=Color.rgb(113,76,196),RED=Color.rgb(224,74,91),TEXT=Color.rgb(33,37,59),MUTED=Color.rgb(100,106,130),BG=Color.rgb(244,247,252);

    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);getWindow().setNavigationBarColor(NAVY);p=getSharedPreferences("data52",0);load();if(!p.getBoolean("logged",false))login();else home();}
    void load(){coins=p.getInt("coins",0);level=p.getInt("level",1);child=p.getString("child","Meu Filho");avatar=p.getString("avatar","🦸‍♂️ Herói");username=p.getString("username","");}
    int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
    TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setGravity(Gravity.CENTER_VERTICAL);t.setPadding(dp(8),dp(5),dp(8),dp(5));return t;}
    GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}
    GradientDrawable gradient(int a,int b,int r){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});g.setCornerRadius(dp(r));return g;}
    Button button(String s,int color){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setGravity(Gravity.CENTER);b.setBackground(gradient(color,Color.rgb(Math.max(0,Color.red(color)-25)),Math.max(0,Color.green(color)-25),Math.max(0,Color.blue(color)-25),18));b.setElevation(dp(2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(54));lp.setMargins(0,dp(6),0,dp(6));b.setLayoutParams(lp);return b;}
    GradientDrawable gradient(int a,int r,int g,int bl,int radius){return gradient3(a,Color.rgb(r,g,bl),radius);}
    GradientDrawable gradient3(int a,int b,int radius){GradientDrawable x=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{a,b});x.setCornerRadius(dp(radius));return x;}
    void base(String title,String sub){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(14),dp(8),dp(14),dp(10));root.setBackgroundColor(BG);setContentView(root);LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);TextView back=text("‹",38,NAVY);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->home());bar.addView(back,new LinearLayout.LayoutParams(dp(45),dp(56)));LinearLayout tt=new LinearLayout(this);tt.setOrientation(LinearLayout.VERTICAL);TextView h=text(title,21,TEXT);h.setTypeface(null,1);tt.addView(h,new LinearLayout.LayoutParams(-1,dp(31)));if(sub!=null)tt.addView(text(sub,12,MUTED),new LinearLayout.LayoutParams(-1,dp(22)));bar.addView(tt,new LinearLayout.LayoutParams(0,dp(56),1));root.addView(bar);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
    void add(String s,int c,View.OnClickListener l){Button b=button(s,c);b.setOnClickListener(l);content.addView(b);}
    void section(String s){TextView t=text(s,14,MUTED);t.setTypeface(null,1);t.setPadding(dp(6),dp(13),dp(6),dp(3));content.addView(t);}
    void card(String s,float z){TextView t=text(s,z,TEXT);t.setBackground(bg(Color.WHITE,20));t.setPadding(dp(17),dp(14),dp(17),dp(14));t.setElevation(dp(2));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,LinearLayout.LayoutParams.WRAP_CONTENT);lp.setMargins(0,dp(5),0,dp(10));content.addView(t,lp);}
    void save(){p.edit().putInt("coins",coins).putInt("level",level).putString("child",child).putString("avatar",avatar).putString("username",username).apply();}

    void login(){base("MESTRE DA TABUADA 5.2","Sua aventura matemática começa aqui");MascotView m=new MascotView(this);m.setBackground(gradient3(NAVY,Color.rgb(40,78,135),25));content.addView(m,new LinearLayout.LayoutParams(-1,dp(210)));section("ENTRAR");EditText email=new EditText(this);email.setHint("E-mail ou usuário");email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);content.addView(email);EditText pass=new EditText(this);pass.setHint("Senha");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(pass);add("🔐 Entrar",GREEN,v->{String u=email.getText().toString().trim();String pw=pass.getText().toString();if(u.isEmpty()||pw.isEmpty()){toast("Preencha usuário e senha.");return;}if(p.getString("login_user","").equals(u)&&p.getString("login_pass","").equals(pw)){username=u;p.edit().putBoolean("logged",true).apply();load();home();}else toast("Usuário ou senha incorretos.");});add("✨ Criar conta",BLUE,v->register());card("🔒 Seus dados de login ficam protegidos no dispositivo nesta versão. A sincronização online entre celulares pode ser adicionada com um serviço de autenticação na próxima etapa.",13);}
    void register(){base("Criar conta","Cadastre o perfil da família");EditText email=new EditText(this);email.setHint("E-mail ou usuário");email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);content.addView(email);EditText pass=new EditText(this);pass.setHint("Senha");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);content.addView(pass);EditText name=new EditText(this);name.setHint("Nome da criança");content.addView(name);add("🚀 Criar minha conta",GREEN,v->{String u=email.getText().toString().trim(),pw=pass.getText().toString(),n=name.getText().toString().trim();if(u.isEmpty()||pw.length()<4||n.isEmpty()){toast("Informe usuário, senha com 4+ caracteres e nome.");return;}p.edit().putString("login_user",u).putString("login_pass",pw).putString("child",n).putBoolean("logged",true).apply();load();home();});add("‹ Voltar ao login",NAVY,v->login());}
    void logout(){p.edit().putBoolean("logged",false).apply();username="";login();}

    void home(){base("MESTRE DA TABUADA 5.2","Aprender também pode ser uma grande aventura!");MascotView hero=new MascotView(this);hero.setBackground(gradient3(NAVY,Color.rgb(38,78,135),28));content.addView(hero,new LinearLayout.LayoutParams(-1,dp(205)));LinearLayout stats=new LinearLayout(this);stats.setGravity(Gravity.CENTER);stats.setBackground(bg(Color.WHITE,20));stats.addView(text(avatar.split(" ")[0]+" "+child,13,TEXT),new LinearLayout.LayoutParams(0,dp(52),1));stats.addView(text("🪙 "+coins,13,TEXT),new LinearLayout.LayoutParams(0,dp(52),1));stats.addView(text("🏅 Nv."+level,13,TEXT),new LinearLayout.LayoutParams(0,dp(52),1));content.addView(stats);section("AVENTURA");add("▶ Jogar agora",GREEN,v->map());add("🗺 Mapa de aventura",ORANGE,v->map());section("TREINAMENTO");add("📚 Modo treino",PURPLE,v->choose(false));add("⚡ Desafio contra o tempo",BLUE,v->choose(true));add("🎁 Tabuada surpresa",ORANGE,v->start(0,false));section("RECOMPENSAS");add("🛍 Avatar, loja e personalização",PURPLE,v->avatarHub());add("🏆 Conquistas",BLUE,v->achievements());add("🎁 Recompensa diária",GREEN,v->daily());section("FAMÍLIA");add("👨‍👩‍👧 Área dos pais",Color.rgb(22,143,132),v->parents());add("⚙ Configurações",Color.DKGRAY,v->settings());add("🚪 Sair da conta",RED,v->logout());TextView cr=text("Desenvolvido por Daniel Marques via IA • versão 5.2",11,MUTED);cr.setGravity(Gravity.CENTER);content.addView(cr,new LinearLayout.LayoutParams(-1,dp(42)));}

    void map(){base("Mapa de aventura","Quatro mundos e dez fases");card("⭐ "+totalStars()+" estrelas conquistadas\n🏅 Nível "+level+" • 🪙 "+coins+" moedas",17);world("🌳","Mundo 1","Floresta da Tabuada",1,5,GREEN,true);world("🏔","Mundo 2","Montanha dos Números",6,7,BLUE,p.getInt("best_5",0)>=5);world("🚀","Mundo 3","Espaço Matemático",8,9,PURPLE,p.getInt("best_7",0)>=5);world("🏰","Mundo 4","Castelo do Mestre",10,10,ORANGE,p.getInt("best_9",0)>=5);}
    void world(String icon,String w,String n,int a,int b,int c,boolean open){String lock=open?"Desbloqueado":"🔒 Complete o mundo anterior";Button x=button(icon+"  "+w+" • "+n+"\n"+lock,c);x.setEnabled(true);x.setOnClickListener(v->{if(open)phases(a,b);else toast("🔒 "+lock);});content.addView(x);}
    void phases(int a,int b){base("Fases","Escolha sua missão");for(int i=a;i<=b;i++){final int n=i;int best=p.getInt("best_"+i,0);boolean open=i==a||p.getInt("best_"+(i-1),0)>=5;add((open?"▶ ":"🔒 ")+"Fase "+i+" • "+stars(best),open?BLUE:MUTED,v->{if(open)start(n,false);});}}
    String stars(int b){return b>=10?"★★★":b>=7?"★★☆":b>=5?"★☆☆":"☆☆☆";}int totalStars(){int z=0;for(int i=1;i<=10;i++){int b=p.getInt("best_"+i,0);z+=b>=10?3:b>=7?2:b>=5?1:0;}return z;}
    void choose(boolean t){base(t?"⚡ Desafio contra o tempo":"📚 Modo treino",t?"30 segundos":"Pratique no seu ritmo");for(int i=1;i<=10;i++){final int n=i;add("✖ Tabuada do "+i,t?BLUE:PURPLE,v->start(n,t));}add("🎲 Mistura surpresa",ORANGE,v->start(0,t));}
    void start(int n,boolean t){table=n;timed=t;score=0;correct=0;lives=3;streak=0;question=0;ask();}
    void ask(){base(timed?"⚡ Desafio":"Fase "+(table==0?"Surpresa":table),timed?"30 segundos":"10 questões");card("❤️ "+lives+"   ⭐ "+score+"   🔥 "+streak+(timed?"   ⏱ 30s":""),16);int a=table==0?1+rnd.nextInt(10):table;int b=1+rnd.nextInt(10);final int ans=a*b;TextView qv=text("Quanto é  "+a+" × "+b+" ?",28,TEXT);qv.setGravity(Gravity.CENTER);qv.setBackground(bg(Color.WHITE,24));content.addView(qv,new LinearLayout.LayoutParams(-1,dp(110)));EditText e=new EditText(this);e.setHint("Digite a resposta");e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);e.setTextSize(22);content.addView(e,new LinearLayout.LayoutParams(-1,dp(60)));add("✓ Responder",GREEN,v->{String s=e.getText().toString().trim();if(s.isEmpty()){toast("Digite uma resposta.");return;}if(Integer.parseInt(s)==ans){correct++;streak++;score+=10+streak*2;coins+=2;toast("🎉 Acertou! +pontos");}else{lives--;streak=0;toast("💡 Resposta correta: "+ans);}question++;save();if(lives<=0||question>=10)end();else ask();});add("💡 Pular",ORANGE,v->{streak=0;question++;if(question>=10)end();else ask();});add("✕ Sair",NAVY,v->home());}
    void end(){if(table>0&&correct>p.getInt("best_"+table,0))p.edit().putInt("best_"+table,correct).apply();if(timed&&correct>p.getInt("timed_best",0))p.edit().putInt("timed_best",correct).apply();level=Math.max(level,1+(totalCorrect()/100));save();base("🏁 Missão concluída","Seu resultado");card((correct==10?"🌟 PERFEITO!":"👏 Continue praticando!")+"\n\n🎯 "+correct+"/10 acertos\n⭐ "+score+" pontos\n🪙 "+coins+" moedas\n🏅 Nível "+level,19);add("▶ Jogar novamente",GREEN,v->start(table,timed));add("🗺 Mapa",ORANGE,v->map());add("🏠 Início",NAVY,v->home());}
    int totalCorrect(){int x=0;for(int i=1;i<=10;i++)x+=p.getInt("best_"+i,0);return x;}

    void avatarHub(){base("🧑‍🚀 Avatar e Loja","Personalize seu personagem");card("Avatar atual: "+avatar+"\nMoedas: 🪙 "+coins,18);String[] n={"🦸‍♂️ Herói","🦊 Raposa","🐼 Panda","🤖 Robô","🐲 Dragão","🚀 Astronauta","🧙 Mago","🥷 Ninja"};int[] price={0,25,50,75,120,180,240,300};for(int i=0;i<n.length;i++){final int ix=i;String key="own_"+i;boolean own=i==0||p.getBoolean(key,false);add(n[i]+"  "+(own?"✓ Usar":"🪙 "+price[i]),i%2==0?PURPLE:BLUE,v->{if(own){avatar=n[ix];save();avatarHub();}else if(coins>=price[ix]){coins-=price[ix];p.edit().putBoolean(key,true).apply();avatar=n[ix];save();avatarHub();}else toast("Faltam "+(price[ix]-coins)+" moedas.");});}add("🎨 Editar nome do perfil",ORANGE,v->editProfile());}
    void editProfile(){final EditText e=new EditText(this);e.setText(child);new AlertDialog.Builder(this).setTitle("👤 Nome do perfil").setView(e).setPositiveButton("Salvar",(d,w)->{child=e.getText().toString().trim();if(child.isEmpty())child="Meu Filho";save();avatarHub();}).setNegativeButton("Cancelar",null).show();}
    void achievements(){base("🏆 Conquistas","Metas e recompensas");int t=totalCorrect();ach("🥉","Primeira vitória","5 acertos","Complete pelo menos 5 acertos",t>=5);ach("🔥","Sequência de estudo","10 acertos","Alcance 10 acertos",t>=10);ach("⭐","Mestre","50 acertos","Alcance 50 acertos",t>=50);ach("🗺","Explorador","30 acertos","Avance pelos mundos",t>=30);ach("⚡","Velocista","10 no tempo","Faça 10 acertos no desafio",p.getInt("timed_best",0)>=10);}
    void ach(String i,String t,String d,String x,boolean ok){card(i+"  "+t+"\n"+d+" • "+(ok?"✓ Conquistada":"🔒 Bloqueada"),15);}
    void daily(){String today=new SimpleDateFormat("yyyyMMdd",Locale.US).format(new Date());String last=p.getString("daily","");base("🎁 Recompensa diária","Bônus por voltar todos os dias");if(!today.equals(last)){coins+=20;p.edit().putString("daily",today).apply();save();card("🎉 Baú aberto!\n+20 moedas",20);}else card("⏳ Recompensa já recebida hoje.\nVolte amanhã!",18);add("🏠 Início",NAVY,v->home());}
    void parents(){final EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER);e.setGravity(Gravity.CENTER);new AlertDialog.Builder(this).setTitle("🔐 Área dos pais").setMessage("Resolva para entrar: 7 + 5 = ?").setView(e).setPositiveButton("Entrar",(d,w)->{if("12".equals(e.getText().toString().trim()))parentPanel();else toast("Resposta incorreta.");}).setNegativeButton("Cancelar",null).show();}
    void parentPanel(){base("👨‍👩‍👧 Área dos pais","Acompanhamento do aprendizado");card("Perfil: "+child+"\n🏅 Nível "+level+"   🪙 "+coins+"\n🎯 "+totalCorrect()+" melhores acertos registrados",17);section("DESEMPENHO");for(int i=1;i<=10;i++)card("Tabuada "+i+"   "+p.getInt("best_"+i,0)+"/10   "+stars(p.getInt("best_"+i,0)),14);add("📈 Gráfico de progresso",BLUE,v->progress());}
    void progress(){base("📈 Progresso","Evolução por tabuada");for(int i=1;i<=10;i++){int b=p.getInt("best_"+i,0);TextView t=text("Tabuada "+i+"   "+b+"/10   "+(b*10)+"%",14,TEXT);t.setBackground(bg(Color.WHITE,15));content.addView(t,new LinearLayout.LayoutParams(-1,dp(45)));ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setProgress(b*10);content.addView(pb,new LinearLayout.LayoutParams(-1,dp(12)));}}
    void settings(){base("⚙ Configurações","Preferências da família");card("👤 Conta: "+username+"\n👦 Criança: "+child+"\n🧑 Avatar: "+avatar+"\n🔊 Sons: ativos\n🌎 Idioma: Português",15);add("👤 Alterar perfil",BLUE,v->editProfile());add("🧹 Limpar progresso",RED,v->new AlertDialog.Builder(this).setTitle("Limpar progresso?").setMessage("Apaga estrelas, moedas, níveis e fases, mas mantém a conta.").setNegativeButton("Cancelar",null).setPositiveButton("Limpar",(d,w)->{p.edit().clear().putBoolean("logged",true).putString("login_user",username).apply();load();home();}).show());add("ℹ Sobre",NAVY,v->new AlertDialog.Builder(this).setTitle("Mestre da Tabuada 5.2").setMessage("Jogo educativo de matemática.\n\nDesenvolvido por Daniel Marques via IA.").setPositiveButton("OK",null).show());}
    void hide(View v){((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(v.getWindowToken(),0);}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    @Override public void onBackPressed(){home();}

    class MascotView extends View{Paint q=new Paint(3);MascotView(Context c){super(c);q.setTypeface(Typeface.DEFAULT_BOLD);}protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();q.setColor(Color.argb(35,255,255,255));c.drawCircle(w*.15f,h*.2f,dp(30),q);c.drawCircle(w*.85f,h*.25f,dp(42),q);q.setColor(Color.rgb(255,202,145));c.drawCircle(w*.5f,h*.42f,dp(48),q);q.setColor(Color.rgb(83,48,32));c.drawCircle(w*.5f,h*.29f,dp(50),q);q.setColor(Color.rgb(255,202,145));c.drawCircle(w*.5f,h*.40f,dp(40),q);q.setColor(Color.WHITE);c.drawCircle(w*.43f,h*.40f,dp(7),q);c.drawCircle(w*.57f,h*.40f,dp(7),q);q.setColor(TEXT);c.drawCircle(w*.43f,h*.40f,dp(3),q);c.drawCircle(w*.57f,h*.40f,dp(3),q);q.setColor(Color.rgb(225,80,90));c.drawOval(w*.47f,h*.45f,w*.53f,h*.50f,q);q.setColor(Color.rgb(38,99,180));c.drawRoundRect(w*.36f,h*.56f,w*.64f,h*.86f,dp(30),dp(30),q);q.setColor(GOLD);c.drawCircle(w*.5f,h*.67f,dp(18),q);q.setColor(Color.WHITE);q.setTextAlign(Paint.Align.CENTER);q.setTextSize(dp(15));c.drawText("M",w*.5f,h*.675f,q);q.setTextSize(dp(15));c.drawText("MESTRE DA TABUADA",w*.5f,h*.95f,q);}}
}
